version: "3.9"

services:
  app:
    build: .
    container_name: sched-links-tg
    ports:
      - "8888:8888"
    env_file:
      - .env
    environment:
      NETLIFY_DEV_DISABLE_EDGE_HANDLERS: "1"
      NETLIFY_DEV_HOST: "0.0.0.0"
    command: ["sh", "-c", "NETLIFY_DEV_DISABLE_EDGE_HANDLERS=1 NETLIFY_DEV_HOST=0.0.0.0 netlify dev --port=8888"]
